plugins {
    id "net.fabricmc.fabric-loom-remap" version "${loom_version}"
    id "com.modrinth.minotaur" version "2.+"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

repositories {
    maven { url "https://maven.terraformersmc.com/" }
    maven { url "https://maven.wispforest.io/" }
    maven { url "https://jitpack.io/" }
    maven { url "https://api.modrinth.com/maven" }
    maven { url "https://maven.gegy.dev/" }
}

dependencies {
    // Required dependencies
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    annotationProcessor modImplementation("io.wispforest:owo-lib:${project.owo_lib_version}")
    implementation "com.github.ben-manes.caffeine:caffeine:${project.caffeine_version}"
    include "com.github.ben-manes.caffeine:caffeine:${project.caffeine_version}"

    // Local dependencies
    modLocalRuntime "com.terraformersmc:modmenu:${project.modmenu_version}"
    modLocalRuntime "maven.modrinth:sodium:${project.sodium_version}"
    modLocalRuntime "maven.modrinth:lithium:${project.lithium_version}"
    modLocalRuntime "dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:${project.lambdynamiclights_version}"
}

fabricApi {
    configureDataGeneration {
        client = true
    }

    configureTests {
        eula = true
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "totally_lit" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

tasks.withType(Jar).configureEach {
    from("LICENSE")
}

modrinth {
    if (project.version.contains("alpha")) {
        versionType = "alpha"
    } else if (project.version.contains("beta")) {
        versionType = "beta"
    }

    token = System.getenv("MODRINTH_TOKEN")
    projectId = "hbKDMT6l"
    uploadFile = remapJar
    additionalFiles = [remapSourcesJar, javadocJar]
    loaders = ["fabric", "quilt"]
    syncBodyFrom = rootProject.file("README.md").text
    dependencies {
        required.project "fabric-api"
        required.project "owo-lib"
        optional.project "modmenu"
        incompatible.project "hardcore-torches"
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
