org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Required dependencies
minecraft=1.21.4
mappings=1.21.4+build.8
fabric_loader=0.16.10
fabric_api=0.116.1+1.21.4
owo_lib=0.12.20+1.21.4

# Local dependencies
modmenu=13.0.2
sodium=mc1.21.4-0.6.7-fabric
lithium=mc1.21.4-0.14.7-fabric
noisium=2.5.0+mc1.21.4
c2me=0.3.1.1.0+1.21.4
scalablelux=0.1.1+fabric.452731d
ferritecore=7.1.1-fabric
patchouli=1.21-87-FABRIC
rei=16.0.783
emi=1.1.16+1.21.1+fabric
lambdynamiclights=4.0.1+1.21.4

# Project detail
mod_version=1.0.0+1.21.4
maven_group=io.github.realguyman
archives_base_name=totally_lit
