org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Required dependencies
minecraft_version=26.1.2
loom_version=1.16-SNAPSHOT
fabric_loader_version=0.19.3
fabric_api_version=0.151.0+26.1.2
owo_lib_version=0.13.0+26.1
caffeine_version=3.2.4

# Local dependencies
modmenu_version=18.0.0-beta.1
lithium_version=mc26.1.2-0.24.5-fabric
lambdynamiclights_version=4.10.2+26.1.2

# Project details
mod_version=1.2.1+1.21.11
maven_group=io.github.realguyman
archives_base_name=totally_lit
