org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Required dependencies
minecraft=1.21.11
loom=1.16-SNAPSHOT
mappings=1.21.11+build.6
fabric_loader=0.19.2
fabric_api=0.141.4+1.21.11
owo_lib=0.13.0+1.21.11

# Local dependencies
modmenu=17.0.0
sodium=mc1.21.11-0.8.12-fabric
lithium=mc1.21.11-0.21.4-fabric
lambdynamiclights=4.9.1+1.21.11
# Project details
mod_version=1.2.0+1.21.11
maven_group=io.github.realguyman
archives_base_name=totally_lit
